### ISSUE TITLE
Bug: Sprite Generation for Stream Not Working

### ISSUE THREAD

**Issue by ProfessorLucyfer** [Koi-3088/SysBot.NET#41]
The bot is no longer updating the generated sprite image for what's been traded. 
The sprite_{0} (leaving the IP blank on purpose for example's sake) was functional on the previous release but upon updating to the net7 Build it now is stuck on a previous generated set and will not update.

**Comment by Koi-3088** [comment]
I'm aware, didn't do anything to fix it. It's because of [this](https://github.com/Koi-3088/ForkBot.NET/blob/839a7409f3fe499fd31beb7a9258ebfa5489ea92/SysBot.Pokemon.WinForms/InitUtil.cs#L1), and unrecognized namespace. Basically just disabled at the moment.

**Comment by ProfessorLucyfer** [comment]
Just wanted to make sure it was known, thank you Koi!
