### ISSUE TITLE
Adding Trainer info into DM

### ISSUE THREAD

**Issue by hexbyt3** [Koi-3088/SysBot.NET#42]
I don't know where to request features, but I've tried to add trainer info to DiscordTradeNotifier.cs and nothing I do seems to be working.  I was wondering if it would be a feature worthwhile for you guys to add to this fork?  At the end of the DM where it says:  Trade finished. Enjoy your {(Species)tradedToUser}!" : "Trade finished!" 

It would be nice to also have the users TID/SID so they know it for future trades instead of having to download the pk file and then upload it to the bot to get it.

**Comment by Koi-3088** [comment]
I don't really want to unnecessarily post TID/SID for every completed trade. It's a one-time thing so it's better to use functions that are already designed for it. `$dump` provides that info, as well as a file re-upload like you mentioned.
