### ISSUE TITLE
More than a different raid with sysbot.net

### ISSUE THREAD

**Issue by Matthieu-Vachet** [Koi-3088/SysBot.NET#44]
Good evening. Could someone explain to me how to make Sysbot change from Seed (raid) on its own? I see several Discord or the bot offers several different raids in a row. Thank you very much

Example in photo![image](https://user-images.githubusercontent.com/79032023/224206130-014600aa-92d9-4cea-a76f-56ef40a08eeb.jpeg)

**Comment by Koi-3088** [comment]
Not a feature of this fork. Find and ask the owner of the fork in question.
